### ISSUE TITLE
Unable to run the agent server

### ISSUE THREAD

**Issue by samanvithms2002** [AgoraIO/openai-realtime-python#4]
@plutoless @digitallysavvy @LichKing-2234 @sidsharma27 , While running the installation process, i am unable to start my server. Due to the following issue:
 
![image](https://github.com/user-attachments/assets/193568dd-b8fe-4cce-aeef-5ad05c9e896c)

This is happening due to the non existence of the agora_lib module in the pip package. Please help me in the resolution of this issue.
Thanks

**Comment by digitallysavvy** [comment]
@samanvithms2002, sorry to hear you are running into issues. To help rule out other issues: 

1. What version of Python are you running? If you run `python --version` and `python3 --version` do you see the same version of Python, and is it > 3.11 ?
1. When you ran the pip install, did you run into any issues?

**Comment by samanvithms2002** [comment]
1. im currently using Python 3.9.7
2. No issues while pip installing packages

**Comment by digitallysavvy** [comment]
Python 3.11 or later is required to use this. Please upgrade your Python installation and run the pip install again. 

See [Prerequisites](https://github.com/AgoraIO/openai-realtime-python#prerequisites)

**Comment by samanvithms2002** [comment]
updated the python version to 3.12.3 and re-installed all packages again. Here's the list of packages:
Package                 Version
----------------------- ---------------
agora_python_server_sdk 2.0.8
agora-realtime-ai-api   1.0.7
aiohappyeyeballs        2.4.0
aiohttp                 3.10.6
aiosignal               1.3.1
annotated-types         0.7.0
anyio                   4.4.0
attrs                   24.2.0
black                   24.4.2
Brotli                  1.1.0
certifi                 2024.7.4
cffi                    1.17.1
click                   8.1.7
colorama                0.4.6
colorlog                6.8.2
distro                  1.9.0
frozenlist              1.4.1
h11                     0.14.0
httpcore                1.0.5
httpx                   0.27.0
idna                    3.10
iniconfig               2.0.0
multidict               6.1.0
mypy                    1.10.1
mypy-extensions         1.0.0
numpy                   1.26.4
openai                  1.37.1
pathspec                0.12.1
pip                     24.2
platformdirs            4.2.2
pluggy                  1.5.0
protobuf                5.27.2
psutil                  5.9.8
PyAudio                 0.2.14
pycparser               2.22
pydantic                2.9.2
pydantic_core           2.23.4
pydub                   0.25.1
pyee                    12.0.0
PyJWT                   2.8.0
pytest                  8.2.2
python-dotenv           1.0.1
ruff                    0.5.2
six                     1.16.0
sniffio                 1.3.1
sounddevice             0.4.7
tqdm                    4.66.4
types-protobuf          4.25.0.20240417
-------------
I still am getting the same error
