### ISSUE TITLE
no instructions provided on the server port (in .env file)

### ISSUE THREAD

**Issue by gaviral** [AgoraIO/openai-realtime-python#6]
where do I find the server port information from?

same for chanel_name and uid

**Comment by tpy37** [comment]
I second the above requests. 
I figured out which OpenAI model to use, but should the model name be in all caps? It’d be helpful to show an example in the .env.example file. Also, could we specify the correct API port there? The current setup instructions are a bit unclear.

**Comment by plutoless** [comment]
https://github.com/AgoraIO/openai-realtime-python/blob/57444839cebaf7da591da2c47e29ab77fafa4a8b/realtime_agent/main.py#L261

The server port is being used here. It will use 8080 if not specified. so you can leave it empty. we will update the comments.
